---
apiVersion: v1
kind: Secret
metadata:
  name: test-distribution-agent-registration-key
  namespace: default
stringData:
  registrationKey: «registration-key»
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: kubedock
  namespace: default
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["create", "get", "list", "delete", "watch"]
  - apiGroups: [""]
    resources: ["pods/log"]
    verbs: ["list", "get"]
  - apiGroups: [""]
    resources: ["pods/exec"]
    verbs: ["create"]
  - apiGroups: [""]
    resources: ["services"]
    verbs: ["create", "get", "list", "delete"]
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["create", "get", "list", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: test-distribution-agent-kubedock-binding
  namespace: default
subjects:
  - kind: ServiceAccount
    name: test-distribution-agent
roleRef:
  kind: Role
  name: kubedock
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: test-distribution-agent
  namespace: default
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-distribution-agent
  namespace: default
  labels:
    app.kubernetes.io/instance: test-distribution-agent-«pool-id»
    app.kubernetes.io/part-of: gradle-enterprise
    app.kubernetes.io/component: test-distribution-agent
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/instance: test-distribution-agent-«pool-id»
      app.kubernetes.io/part-of: gradle-enterprise
      app.kubernetes.io/component: test-distribution-agent
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: test-distribution-agent-«pool-id»
        app.kubernetes.io/part-of: gradle-enterprise
        app.kubernetes.io/component: test-distribution-agent
    spec:
      serviceAccountName: test-distribution-agent
      securityContext:
        runAsUser: 999
        runAsGroup: 0
        fsGroup: 0
      terminationGracePeriodSeconds: 600
      containers:
        - name: kubedock
          image: joyrex2001/kubedock:0.16.0
          args:
            - server
            - --reverse-proxy
            - --unix-socket
            - /var/run/docker.sock
          volumeMounts:
            - name: kubedock-socket
              mountPath: /var/run
        - name: test-distribution-agent
          image: gradle/develocity-test-distribution-agent
          resources:
            requests:
              memory: 1Gi
              cpu: 2
            limits:
              memory: 4Gi
              cpu: 2
          env:
            - name: TESTCONTAINERS_RYUK_DISABLED
              value: 'true'
            - name: TESTCONTAINERS_CHECKS_DISABLE
              value: 'true'
            - name: TEST_DISTRIBUTION_AGENT_SERVER
              value: «server-url»
            - name: TEST_DISTRIBUTION_AGENT_REGISTRATION_KEY
              valueFrom:
                secretKeyRef:
                  name: test-distribution-agent-registration-key
                  key: registrationKey
            - name: TEST_DISTRIBUTION_AGENT_POOL
              value: «pool-id»
          volumeMounts:
            - name: kubedock-socket
              mountPath: /var/run
      volumes:
        - name: kubedock-socket
          emptyDir: { }
